services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=wrolpi
      - POSTGRES_PASSWORD=wrolpi
    ports:
      - ${DB_PORT-5432}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: lrnselfreliance/wrolpi:wrolpi-api-latest
    depends_on:
      - db
    ports:
      - ${API_PORT-8081}:8081
    volumes:
      - media_data:/media/wrolpi
    user: '${UID-1000}:${GID-1000}'
    healthcheck:
      test: ['CMD-SHELL', 'curl http://api:8081/api/echo']
      interval: 2m

  archive:
    image: lrnselfreliance/wrolpi:wrolpi-archive-latest
    ports:
      - ${ARCHIVE_PORT-8083}:8080
    healthcheck:
      test: ['CMD-SHELL', 'curl http://archive:8080/']
      interval: 2m

  app:
    image: lrnselfreliance/wrolpi:wrolpi-app-latest
    depends_on:
      - api
    ports:
      - ${APP_PORT-3000}:3000
    environment:
      - WDS_SOCKET_PORT=0
    healthcheck:
      test: ['CMD-SHELL', 'curl http://app:3000/']
      interval: 1m
    user: '${UID-1000}:${GID-1000}'
    command: 'serve -s build -l 3000'

  map:
    image: overv/openstreetmap-tile-server:v1.6.0
    volumes:
      - openstreetmap_data:/var/lib/postgresql/12/main
      - openstreetmap_rendered_tiles:/var/lib/mod_tile
    command: 'run'
    shm_size: 1g
    healthcheck:
      test: ['CMD-SHELL', 'curl http://map:80/']
      interval: 1m

  map_https:
    image: lrnselfreliance/wrolpi:wrolpi-map_https-latest
    depends_on:
      - map
    ports:
      - ${MAP_HTTPS_PORT-8084}:443
    healthcheck:
      test: ['CMD-SHELL', 'curl http://map_https:443/']
      interval: 1m

  web:
    image: lrnselfreliance/wrolpi:wrolpi-web-latest
    depends_on:
      - app
    ports:
      - ${WEB_PORT-8080}:80
      - ${WEB_HTTPS_PORT-8443}:443
    volumes:
      - media_data:/opt/media
    healthcheck:
      test: ['CMD-SHELL', 'curl http://web:80/']
      interval: 1m

  zim:
    image: lrnselfreliance/wrolpi:wrolpi-zim-latest
    volumes:
      - media_data:/media/wrolpi
    healthcheck:
      test: ['CMD-SHELL', 'curl http://zim:80/']
      interval: 1m

  zim_https:
    image: lrnselfreliance/wrolpi:wrolpi-zim_https-latest
    depends_on:
      - zim
    ports:
      - ${ZIM_HTTPS_PORT-8085}:443
    healthcheck:
      test: ['CMD-SHELL', 'curl http://zim_https:443/']
      interval: 1m

  help:
    image: lrnselfreliance/wrolpi:wrolpi-help-latest
    healthcheck:
      test: ['CMD-SHELL', 'curl http://help:8086/']
      interval: 1m

  help_https:
    image: lrnselfreliance/wrolpi:wrolpi-help_https-latest
    depends_on:
      - help
    ports:
      - ${HELP_HTTPS_PORT-8086}:443
    healthcheck:
      test: ['CMD-SHELL', 'curl http://help_https:443/']
      interval: 1m

volumes:
  pg_data:
  media_data:
  openstreetmap_data:
  openstreetmap_rendered_tiles: