"""Add file_format to Collection

Revision ID: 7611b5117406
Revises: 0ad5cb3b9a33
Create Date: 2026-01-02 07:06:56.347484

"""
import os
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '7611b5117406'
down_revision = '0ad5cb3b9a33'
branch_labels = None
depends_on = None

DOCKERIZED = True if os.environ.get('DOCKER', '').lower().startswith('t') else False


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('file_format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'file_format')
    # ### end Alembic commands ###
