ISO_639_CODES = {
    "aa": "Afar",
    "aar": "Afar",
    "ab": "Abkhazian",
    "abk": "Abkhazian",
    "ace": "Achinese",
    "ach": "Acoli",
    "ada": "Adangme",
    "ady": "Adyghe; Adygei",
    "ae": "Avestan",
    "af": "Afrikaans",
    "afa": "Afro-Asiatic languages",
    "afh": "Afrihili",
    "afr": "Afrikaans",
    "ain": "Ainu",
    "ak": "Akan",
    "aka": "Akan",
    "akk": "Akkadian",
    "ale": "Aleut",
    "alg": "Algonquian languages",
    "alt": "Southern Altai",
    "am": "Amharic",
    "amh": "Amharic",
    "an": "Aragonese",
    "ang": "English, Old",
    "anp": "Angika",
    "apa": "Apache languages",
    "ar": "Arabic",
    "ara": "Arabic",
    "arc": "Official Aramaic",
    "arg": "Aragonese",
    "arn": "Mapudungun; Mapuche",
    "arp": "Arapaho",
    "art": "Artificial languages",
    "arw": "Arawak",
    "as": "Assamese",
    "asm": "Assamese",
    "ast": "Asturian; Bable; Leonese; Asturleonese",
    "ath": "Athapascan languages",
    "aus": "Australian languages",
    "av": "Avaric",
    "ava": "Avaric",
    "ave": "Avestan",
    "awa": "Awadhi",
    "ay": "Aymara",
    "aym": "Aymara",
    "az": "Azerbaijani",
    "aze": "Azerbaijani",
    "ba": "Bashkir",
    "bad": "Banda languages",
    "bai": "Bamileke languages",
    "bak": "Bashkir",
    "bal": "Baluchi",
    "bam": "Bambara",
    "ban": "Balinese",
    "bas": "Basa",
    "bat": "Baltic languages",
    "be": "Belarusian",
    "bej": "Beja; Bedawiyet",
    "bel": "Belarusian",
    "bem": "Bemba",
    "ben": "Bengali",
    "ber": "Berber languages",
    "bg": "Bulgarian",
    "bh": "Bihari languages",
    "bho": "Bhojpuri",
    "bi": "Bislama",
    "bih": "Bihari languages",
    "bik": "Bikol",
    "bin": "Bini; Edo",
    "bis": "Bislama",
    "bla": "Siksika",
    "bm": "Bambara",
    "bn": "Bengali",
    "bnt": "Bantu languages",
    "bo": "Tibetan",
    "bod": "Tibetan",
    "bos": "Bosnian",
    "br": "Breton",
    "bra": "Braj",
    "bre": "Breton",
    "bs": "Bosnian",
    "btk": "Batak languages",
    "bua": "Buriat",
    "bug": "Buginese",
    "bul": "Bulgarian",
    "byn": "Blin; Bilin",
    "ca": "Catalan; Valencian",
    "cad": "Caddo",
    "cai": "Central American Indian languages",
    "car": "Galibi Carib",
    "cat": "Catalan; Valencian",
    "cau": "Caucasian languages",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "cel": "Celtic languages",
    "ces": "Czech",
    "ch": "Chamorro",
    "cha": "Chamorro",
    "chb": "Chibcha",
    "che": "Chechen",
    "chg": "Chagatai",
    "chk": "Chuukese",
    "chm": "Mari",
    "chn": "Chinook jargon",
    "cho": "Choctaw",
    "chp": "Chipewyan; Dene Suline",
    "chr": "Cherokee",
    "chu": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    "chv": "Chuvash",
    "chy": "Cheyenne",
    "cmc": "Chamic languages",
    "cnr": "Montenegrin",
    "co": "Corsican",
    "cop": "Coptic",
    "cor": "Cornish",
    "cos": "Corsican",
    "cpe": "Creoles and pidgins, English based",
    "cpf": "Creoles and pidgins, French-based",
    "cpp": "Creoles and pidgins, Portuguese-based",
    "cr": "Cree",
    "cre": "Cree",
    "crh": "Crimean Tatar; Crimean Turkish",
    "crp": "Creoles and pidgins",
    "cs": "Czech",
    "csb": "Kashubian",
    "cu": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    "cus": "Cushitic languages",
    "cv": "Chuvash",
    "cy": "Welsh",
    "cym": "Welsh",
    "da": "Danish",
    "dak": "Dakota",
    "dan": "Danish",
    "dar": "Dargwa",
    "day": "Land Dayak languages",
    "de": "German",
    "del": "Delaware",
    "den": "Slave (Athapascan)",
    "deu": "German",
    "dgr": "Dogrib",
    "din": "Dinka",
    "div": "Divehi; Dhivehi; Maldivian",
    "doi": "Dogri",
    "dra": "Dravidian languages",
    "dsb": "Lower Sorbian",
    "dua": "Duala",
    "dum": "Dutch, Middle (ca.1050-1350)",
    "dv": "Divehi; Dhivehi; Maldivian",
    "dyu": "Dyula",
    "dz": "Dzongkha",
    "dzo": "Dzongkha",
    "ee": "Ewe",
    "efi": "Efik",
    "egy": "Egyptian (Ancient)",
    "eka": "Ekajuk",
    "el": "Greek, Modern (1453-)",
    "ell": "Greek, Modern (1453-)",
    "elx": "Elamite",
    "en": "English",
    "en-GB": "British English",  # Not official
    "eng": "English",
    "enm": "English, Middle (1100-1500)",
    "eo": "Esperanto",
    "epo": "Esperanto",
    "es": "Spanish; Castilian",
    "est": "Estonian",
    "et": "Estonian",
    "eu": "Basque",
    "eus": "Basque",
    "ewe": "Ewe",
    "ewo": "Ewondo",
    "fa": "Persian",
    "fan": "Fang",
    "fao": "Faroese",
    "fas": "Persian",
    "fat": "Fanti",
    "ff": "Fulah",
    "fi": "Finnish",
    "fij": "Fijian",
    "fil": "Filipino; Pilipino",
    "fin": "Finnish",
    "fiu": "Finno-Ugrian languages",
    "fj": "Fijian",
    "fo": "Faroese",
    "fon": "Fon",
    "fr": "French",
    "fra": "French",
    "frm": "French, Middle (ca.1400-1600)",
    "fro": "French, Old (842-ca.1400)",
    "frr": "Northern Frisian",
    "frs": "Eastern Frisian",
    "fry": "Western Frisian",
    "ful": "Fulah",
    "fur": "Friulian",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gaa": "Ga",
    "gay": "Gayo",
    "gba": "Gbaya",
    "gd": "Gaelic; Scottish Gaelic",
    "gem": "Germanic languages",
    "gez": "Geez",
    "gil": "Gilbertese",
    "gl": "Galician",
    "gla": "Gaelic; Scottish Gaelic",
    "gle": "Irish",
    "glg": "Galician",
    "glv": "Manx",
    "gmh": "German, Middle High (ca.1050-1500)",
    "gn": "Guarani",
    "goh": "German, Old High (ca.750-1050)",
    "gon": "Gondi",
    "gor": "Gorontalo",
    "got": "Gothic",
    "grb": "Grebo",
    "grc": "Greek, Ancient (to 1453)",
    "grn": "Guarani",
    "gsw": "Swiss German; Alemannic; Alsatian",
    "gu": "Gujarati",
    "guj": "Gujarati",
    "gv": "Manx",
    "gwi": "Gwich'in",
    "ha": "Hausa",
    "hai": "Haida",
    "hat": "Haitian; Haitian Creole",
    "hau": "Hausa",
    "haw": "Hawaiian",
    "he": "Hebrew",
    "heb": "Hebrew",
    "her": "Herero",
    "hi": "Hindi",
    "hil": "Hiligaynon",
    "him": "Himachali languages; Western Pahari languages",
    "hin": "Hindi",
    "hit": "Hittite",
    "hmn": "Hmong; Mong",
    "hmo": "Hiri Motu",
    "ho": "Hiri Motu",
    "hr": "Croatian",
    "hrv": "Croatian",
    "hsb": "Upper Sorbian",
    "ht": "Haitian; Haitian Creole",
    "hu": "Hungarian",
    "hun": "Hungarian",
    "hup": "Hupa",
    "hy": "Armenian",
    "hye": "Armenian",
    "hz": "Herero",
    "ia": "Interlingua",
    "iba": "Iban",
    "ibo": "Igbo",
    "id": "Indonesian",
    "ido": "Ido",
    "ie": "Interlingue; Occidental",
    "ig": "Igbo",
    "ii": "Sichuan Yi; Nuosu",
    "iii": "Sichuan Yi; Nuosu",
    "ijo": "Ijo languages",
    "ik": "Inupiaq",
    "iku": "Inuktitut",
    "ile": "Interlingue; Occidental",
    "ilo": "Iloko",
    "ina": "Interlingua",
    "inc": "Indic languages",
    "ind": "Indonesian",
    "ine": "Indo-European languages",
    "inh": "Ingush",
    "io": "Ido",
    "ipk": "Inupiaq",
    "ira": "Iranian languages",
    "iro": "Iroquoian languages",
    "is": "Icelandic",
    "isl": "Icelandic",
    "it": "Italian",
    "ita": "Italian",
    "iu": "Inuktitut",
    "ja": "Japanese",
    "jav": "Javanese",
    "jbo": "Lojban",
    "jpn": "Japanese",
    "jpr": "Judeo-Persian",
    "jrb": "Judeo-Arabic",
    "jv": "Javanese",
    "ka": "Georgian",
    "kaa": "Kara-Kalpak",
    "kab": "Kabyle",
    "kac": "Kachin; Jingpho",
    "kal": "Kalaallisut; Greenlandic",
    "kam": "Kamba",
    "kan": "Kannada",
    "kar": "Karen languages",
    "kas": "Kashmiri",
    "kat": "Georgian",
    "kau": "Kanuri",
    "kaw": "Kawi",
    "kaz": "Kazakh",
    "kbd": "Kabardian",
    "kg": "Kongo",
    "kha": "Khasi",
    "khi": "Khoisan languages",
    "khm": "Central Khmer",
    "kho": "Khotanese; Sakan",
    "ki": "Kikuyu; Gikuyu",
    "kik": "Kikuyu; Gikuyu",
    "kin": "Kinyarwanda",
    "kir": "Kirghiz; Kyrgyz",
    "kj": "Kuanyama; Kwanyama",
    "kk": "Kazakh",
    "kl": "Kalaallisut; Greenlandic",
    "km": "Central Khmer",
    "kmb": "Kimbundu",
    "kn": "Kannada",
    "ko": "Korean",
    "kok": "Konkani",
    "kom": "Komi",
    "kon": "Kongo",
    "kor": "Korean",
    "kos": "Kosraean",
    "kpe": "Kpelle",
    "kr": "Kanuri",
    "krc": "Karachay-Balkar",
    "krl": "Karelian",
    "kro": "Kru languages",
    "kru": "Kurukh",
    "ks": "Kashmiri",
    "ku": "Kurdish",
    "kua": "Kuanyama; Kwanyama",
    "kum": "Kumyk",
    "kur": "Kurdish",
    "kut": "Kutenai",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kirghiz; Kyrgyz",
    "la": "Latin",
    "lad": "Ladino",
    "lah": "Lahnda",
    "lam": "Lamba",
    "lao": "Lao",
    "lat": "Latin",
    "lav": "Latvian",
    "lb": "Luxembourgish; Letzeburgesch",
    "lez": "Lezghian",
    "lg": "Ganda",
    "li": "Limburgan; Limburger; Limburgish",
    "lim": "Limburgan; Limburger; Limburgish",
    "lin": "Lingala",
    "lit": "Lithuanian",
    "ln": "Lingala",
    "lo": "Lao",
    "lol": "Mongo",
    "loz": "Lozi",
    "lt": "Lithuanian",
    "ltz": "Luxembourgish; Letzeburgesch",
    "lu": "Luba-Katanga",
    "lua": "Luba-Lulua",
    "lub": "Luba-Katanga",
    "lug": "Ganda",
    "lui": "Luiseno",
    "lun": "Lunda",
    "luo": "Luo (Kenya and Tanzania)",
    "lus": "Lushai",
    "lv": "Latvian",
    "mad": "Madurese",
    "mag": "Magahi",
    "mah": "Marshallese",
    "mai": "Maithili",
    "mak": "Makasar",
    "mal": "Malayalam",
    "man": "Mandingo",
    "map": "Austronesian languages",
    "mar": "Marathi",
    "mas": "Masai",
    "mdf": "Moksha",
    "mdr": "Mandar",
    "men": "Mende",
    "mg": "Malagasy",
    "mga": "Irish, Middle (900-1200)",
    "mh": "Marshallese",
    "mi": "Maori",
    "mic": "Mi'kmaq; Micmac",
    "min": "Minangkabau",
    "mis": "Uncoded languages",
    "mk": "Macedonian",
    "mkd": "Macedonian",
    "mkh": "Mon-Khmer languages",
    "ml": "Malayalam",
    "mlg": "Malagasy",
    "mlt": "Maltese",
    "mn": "Mongolian",
    "mnc": "Manchu",
    "mni": "Manipuri",
    "mno": "Manobo languages",
    "moh": "Mohawk",
    "mon": "Mongolian",
    "mos": "Mossi",
    "mr": "Marathi",
    "mri": "Maori",
    "ms": "Malay",
    "msa": "Malay",
    "mt": "Maltese",
    "mul": "Multiple languages",
    "mun": "Munda languages",
    "mus": "Creek",
    "mwl": "Mirandese",
    "mwr": "Marwari",
    "my": "Burmese",
    "mya": "Burmese",
    "myn": "Mayan languages",
    "myv": "Erzya",
    "na": "Nauru",
    "nah": "Nahuatl languages",
    "nai": "North American Indian languages",
    "nap": "Neapolitan",
    "nau": "Nauru",
    "nav": "Navajo; Navaho",
    "nb": "Bokmål, Norwegian; Norwegian Bokmål",
    "nbl": "Ndebele, South; South Ndebele",
    "nd": "Ndebele, North; North Ndebele",
    "nde": "Ndebele, North; North Ndebele",
    "ndo": "Ndonga",
    "nds": "Low German; Low Saxon; German, Low; Saxon, Low",
    "ne": "Nepali",
    "nep": "Nepali",
    "new": "Nepal Bhasa; Newari",
    "ng": "Ndonga",
    "nia": "Nias",
    "nic": "Niger-Kordofanian languages",
    "niu": "Niuean",
    "nl": "Dutch; Flemish",
    "nld": "Dutch; Flemish",
    "nn": "Norwegian Nynorsk; Nynorsk, Norwegian",
    "nno": "Norwegian Nynorsk; Nynorsk, Norwegian",
    "no": "Norwegian",
    "nob": "Bokmål, Norwegian; Norwegian Bokmål",
    "nog": "Nogai",
    "non": "Norse, Old",
    "nor": "Norwegian",
    "nqo": "N'Ko",
    "nr": "Ndebele, South; South Ndebele",
    "nso": "Pedi; Sepedi; Northern Sotho",
    "nub": "Nubian languages",
    "nv": "Navajo; Navaho",
    "nwc": "Classical Newari; Old Newari; Classical Nepal Bhasa",
    "ny": "Chichewa; Chewa; Nyanja",
    "nya": "Chichewa; Chewa; Nyanja",
    "nym": "Nyamwezi",
    "nyn": "Nyankole",
    "nyo": "Nyoro",
    "nzi": "Nzima",
    "oc": "Occitan (post 1500)",
    "oci": "Occitan (post 1500)",
    "oj": "Ojibwa",
    "oji": "Ojibwa",
    "om": "Oromo",
    "or": "Oriya",
    "ori": "Oriya",
    "orm": "Oromo",
    "os": "Ossetian; Ossetic",
    "osa": "Osage",
    "oss": "Ossetian; Ossetic",
    "ota": "Turkish, Ottoman (1500-1928)",
    "oto": "Otomian languages",
    "pa": "Panjabi; Punjabi",
    "paa": "Papuan languages",
    "pag": "Pangasinan",
    "pal": "Pahlavi",
    "pam": "Pampanga; Kapampangan",
    "pan": "Panjabi; Punjabi",
    "pap": "Papiamento",
    "pau": "Palauan",
    "peo": "Persian, Old (ca.600-400 B.C.)",
    "phi": "Philippine languages",
    "phn": "Phoenician",
    "pi": "Pali",
    "pl": "Polish",
    "pli": "Pali",
    "pol": "Polish",
    "pon": "Pohnpeian",
    "por": "Portuguese",
    "pra": "Prakrit languages",
    "pro": "Provençal, Old (to 1500);Occitan, Old (to 1500)",
    "ps": "Pushto; Pashto",
    "pt": "Portuguese",
    "pus": "Pushto; Pashto",
    "qaa-qtz": "Reserved for local use",
    "qu": "Quechua",
    "que": "Quechua",
    "raj": "Rajasthani",
    "rap": "Rapanui",
    "rar": "Rarotongan; Cook Islands Maori",
    "rm": "Romansh",
    "rn": "Rundi",
    "ro": "Romanian; Moldavian; Moldovan",
    "roa": "Romance languages",
    "roh": "Romansh",
    "rom": "Romany",
    "ron": "Romanian; Moldavian; Moldovan",
    "ru": "Russian",
    "run": "Rundi",
    "rup": "Aromanian; Arumanian; Macedo-Romanian",
    "rus": "Russian",
    "rw": "Kinyarwanda",
    "sa": "Sanskrit",
    "sad": "Sandawe",
    "sag": "Sango",
    "sah": "Yakut",
    "sai": "South American Indian languages",
    "sal": "Salishan languages",
    "sam": "Samaritan Aramaic",
    "san": "Sanskrit",
    "sas": "Sasak",
    "sat": "Santali",
    "sc": "Sardinian",
    "scn": "Sicilian",
    "sco": "Scots",
    "sd": "Sindhi",
    "se": "Northern Sami",
    "sel": "Selkup",
    "sem": "Semitic languages",
    "sg": "Sango",
    "sga": "Irish, Old (to 900)",
    "sgn": "Sign Languages",
    "shn": "Shan",
    "si": "Sinhala; Sinhalese",
    "sid": "Sidamo",
    "sin": "Sinhala; Sinhalese",
    "sio": "Siouan languages",
    "sit": "Sino-Tibetan languages",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sla": "Slavic languages",
    "slk": "Slovak",
    "slv": "Slovenian",
    "sm": "Samoan",
    "sma": "Southern Sami",
    "sme": "Northern Sami",
    "smi": "Sami languages",
    "smj": "Lule Sami",
    "smn": "Inari Sami",
    "smo": "Samoan",
    "sms": "Skolt Sami",
    "sn": "Shona",
    "sna": "Shona",
    "snd": "Sindhi",
    "snk": "Soninke",
    "so": "Somali",
    "sog": "Sogdian",
    "som": "Somali",
    "son": "Songhai languages",
    "sot": "Sotho, Southern",
    "spa": "Spanish; Castilian",
    "sq": "Albanian",
    "sqi": "Albanian",
    "sr": "Serbian",
    "srd": "Sardinian",
    "srn": "Sranan Tongo",
    "srp": "Serbian",
    "srr": "Serer",
    "ss": "Swati",
    "ssa": "Nilo-Saharan languages",
    "ssw": "Swati",
    "st": "Sotho, Southern",
    "su": "Sundanese",
    "suk": "Sukuma",
    "sun": "Sundanese",
    "sus": "Susu",
    "sux": "Sumerian",
    "sv": "Swedish",
    "sw": "Swahili",
    "swa": "Swahili",
    "swe": "Swedish",
    "syc": "Classical Syriac",
    "syr": "Syriac",
    "ta": "Tamil",
    "tah": "Tahitian",
    "tai": "Tai languages",
    "tam": "Tamil",
    "tat": "Tatar",
    "te": "Telugu",
    "tel": "Telugu",
    "tem": "Timne",
    "ter": "Tereno",
    "tet": "Tetum",
    "tg": "Tajik",
    "tgk": "Tajik",
    "tgl": "Tagalog",
    "th": "Thai",
    "tha": "Thai",
    "ti": "Tigrinya",
    "tig": "Tigre",
    "tir": "Tigrinya",
    "tiv": "Tiv",
    "tk": "Turkmen",
    "tkl": "Tokelau",
    "tl": "Tagalog",
    "tlh": "Klingon; tlhIngan-Hol",
    "tli": "Tlingit",
    "tmh": "Tamashek",
    "tn": "Tswana",
    "to": "Tonga (Tonga Islands)",
    "tog": "Tonga (Nyasa)",
    "ton": "Tonga (Tonga Islands)",
    "tpi": "Tok Pisin",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tsi": "Tsimshian",
    "tsn": "Tswana",
    "tso": "Tsonga",
    "tt": "Tatar",
    "tuk": "Turkmen",
    "tum": "Tumbuka",
    "tup": "Tupi languages",
    "tur": "Turkish",
    "tut": "Altaic languages",
    "tvl": "Tuvalu",
    "tw": "Twi",
    "twi": "Twi",
    "ty": "Tahitian",
    "tyv": "Tuvinian",
    "udm": "Udmurt",
    "ug": "Uighur; Uyghur",
    "uga": "Ugaritic",
    "uig": "Uighur; Uyghur",
    "uk": "Ukrainian",
    "ukr": "Ukrainian",
    "umb": "Umbundu",
    "und": "Undetermined",
    "ur": "Urdu",
    "urd": "Urdu",
    "uz": "Uzbek",
    "uzb": "Uzbek",
    "vai": "Vai",
    "ve": "Venda",
    "ven": "Venda",
    "vi": "Vietnamese",
    "vie": "Vietnamese",
    "vo": "Volapük",
    "vol": "Volapük",
    "vot": "Votic",
    "wa": "Walloon",
    "wak": "Wakashan languages",
    "wal": "Wolaitta; Wolaytta",
    "war": "Waray",
    "was": "Washo",
    "wen": "Sorbian languages",
    "wln": "Walloon",
    "wo": "Wolof",
    "wol": "Wolof",
    "xal": "Kalmyk; Oirat",
    "xh": "Xhosa",
    "xho": "Xhosa",
    "yao": "Yao",
    "yap": "Yapese",
    "yi": "Yiddish",
    "yid": "Yiddish",
    "yo": "Yoruba",
    "yor": "Yoruba",
    "ypk": "Yupik languages",
    "za": "Zhuang; Chuang",
    "zap": "Zapotec",
    "zbl": "Blissymbols; Blissymbolics; Bliss",
    "zen": "Zenaga",
    "zgh": "Standard Moroccan Tamazight",
    "zh": "Chinese",
    "zha": "Zhuang; Chuang",
    "zho": "Chinese",
    "znd": "Zande languages",
    "zu": "Zulu",
    "zul": "Zulu",
    "zun": "Zuni",
    "zxx": "No linguistic content; Not applicable",
    "zza": "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
}

ISO_3166_CODES = {
    'af': 'Afghanistan[b]',
    'ax': 'Åland Islands',
    'al': 'Albania',
    'dz': 'Algeria',
    'as': 'American Samoa',
    'ad': 'Andorra',
    'ao': 'Angola',
    'ai': 'Anguilla',
    'aq': 'Antarctica',
    'ag': 'Antigua and Barbuda',
    'ar': 'Argentina',
    'am': 'Armenia',
    'aw': 'Aruba',
    'au': 'Australia',
    'at': 'Austria',
    'az': 'Azerbaijan',
    'bs': 'Bahamas',
    'bh': 'Bahrain',
    'bd': 'Bangladesh',
    'bb': 'Barbados',
    'by': 'Belarus',
    'be': 'Belgium',
    'bz': 'Belize',
    'bj': 'Benin',
    'bm': 'Bermuda',
    'bt': 'Bhutan',
    'bo': 'Bolivia, Plurinational State of',
    'bq': 'Bonaire, Sint Eustatius and Saba[c]',
    'ba': 'Bosnia and Herzegovina',
    'bw': 'Botswana',
    'bv': 'Bouvet Island',
    'br': 'Brazil',
    'io': 'British Indian Ocean Territory',
    'bn': 'Brunei Darussalam',
    'bg': 'Bulgaria',
    'bf': 'Burkina Faso',
    'bi': 'Burundi',
    'cv': 'Cabo Verde',
    'kh': 'Cambodia',
    'cm': 'Cameroon',
    'ca': 'Canada',
    'ky': 'Cayman Islands',
    'cf': 'Central African Republic',
    'td': 'Chad',
    'cl': 'Chile',
    'cn': 'China[b]',
    'cx': 'Christmas Island',
    'cc': 'Cocos (Keeling) Islands',
    'co': 'Colombia',
    'km': 'Comoros',
    'cg': 'Congo',
    'cd': 'Congo, Democratic Republic of the',
    'ck': 'Cook Islands',
    'cr': 'Costa Rica',
    'ci': "Côte d'Ivoire",
    'hr': 'Croatia',
    'cu': 'Cuba',
    'cw': 'Curaçao',
    'cy': 'Cyprus[b]',
    'cz': 'Czechia',
    'dk': 'Denmark',
    'dj': 'Djibouti',
    'dm': 'Dominica',
    'do': 'Dominican Republic',
    'ec': 'Ecuador',
    'eg': 'Egypt',
    'sv': 'El Salvador',
    'gq': 'Equatorial Guinea',
    'er': 'Eritrea',
    'ee': 'Estonia',
    'sz': 'Eswatini',
    'et': 'Ethiopia',
    'fk': 'Falkland Islands (Malvinas)[b]',
    'fo': 'Faroe Islands',
    'fj': 'Fiji',
    'fi': 'Finland',
    'fr': 'France',
    'gf': 'French Guiana',
    'pf': 'French Polynesia',
    'tf': 'French Southern Territories',
    'ga': 'Gabon',
    'gm': 'Gambia',
    'ge': 'Georgia',
    'de': 'Germany',
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gr': 'Greece',
    'gl': 'Greenland',
    'gd': 'Grenada',
    'gp': 'Guadeloupe',
    'gu': 'Guam',
    'gt': 'Guatemala',
    'gg': 'Guernsey',
    'gn': 'Guinea',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'ht': 'Haiti',
    'hm': 'Heard Island and McDonald Islands',
    'va': 'Holy See',
    'hn': 'Honduras',
    'hk': 'Hong Kong',
    'hu': 'Hungary',
    'is': 'Iceland',
    'in': 'India',
    'id': 'Indonesia',
    'ir': 'Iran, Islamic Republic of',
    'iq': 'Iraq',
    'ie': 'Ireland',
    'im': 'Isle of Man',
    'il': 'Israel',
    'it': 'Italy',
    'jm': 'Jamaica',
    'jp': 'Japan',
    'je': 'Jersey',
    'jo': 'Jordan',
    'kz': 'Kazakhstan',
    'ke': 'Kenya',
    'ki': 'Kiribati',
    'kp': "Korea, Democratic People's Republic of",
    'kr': 'Korea, Republic of',
    'kw': 'Kuwait',
    'kg': 'Kyrgyzstan',
    'la': "Lao People's Democratic Republic",
    'lv': 'Latvia',
    'lb': 'Lebanon',
    'ls': 'Lesotho',
    'lr': 'Liberia',
    'ly': 'Libya',
    'li': 'Liechtenstein',
    'lt': 'Lithuania',
    'lu': 'Luxembourg',
    'mo': 'Macao',
    'mg': 'Madagascar',
    'mw': 'Malawi',
    'my': 'Malaysia',
    'mv': 'Maldives',
    'ml': 'Mali',
    'mt': 'Malta',
    'mh': 'Marshall Islands',
    'mq': 'Martinique',
    'mr': 'Mauritania',
    'mu': 'Mauritius',
    'yt': 'Mayotte',
    'mx': 'Mexico',
    'fm': 'Micronesia, Federated States of',
    'md': 'Moldova, Republic of',
    'mc': 'Monaco',
    'mn': 'Mongolia',
    'me': 'Montenegro',
    'ms': 'Montserrat',
    'ma': 'Morocco',
    'mz': 'Mozambique',
    'mm': 'Myanmar',
    'na': 'Namibia',
    'nr': 'Nauru',
    'np': 'Nepal',
    'nl': 'Netherlands, Kingdom of the',
    'nc': 'New Caledonia',
    'nz': 'New Zealand',
    'ni': 'Nicaragua',
    'ne': 'Niger',
    'ng': 'Nigeria',
    'nu': 'Niue',
    'nf': 'Norfolk Island',
    'mk': 'North Macedonia',
    'mp': 'Northern Mariana Islands',
    'no': 'Norway',
    'om': 'Oman',
    'pk': 'Pakistan',
    'pw': 'Palau',
    'ps': 'Palestine, State of[b]',
    'pa': 'Panama',
    'pg': 'Papua New Guinea',
    'py': 'Paraguay',
    'pe': 'Peru',
    'ph': 'Philippines',
    'pn': 'Pitcairn',
    'pl': 'Poland',
    'pt': 'Portugal',
    'pr': 'Puerto Rico',
    'qa': 'Qatar',
    're': 'Réunion',
    'ro': 'Romania',
    'ru': 'Russian Federation',
    'rw': 'Rwanda',
    'bl': 'Saint Barthélemy',
    'sh': 'Saint Helena, Ascension and Tristan da Cunha[d]',
    'kn': 'Saint Kitts and Nevis',
    'lc': 'Saint Lucia',
    'mf': 'Saint Martin (French part)',
    'pm': 'Saint Pierre and Miquelon',
    'vc': 'Saint Vincent and the Grenadines',
    'ws': 'Samoa',
    'sm': 'San Marino',
    'st': 'Sao Tome and Principe',
    'sa': 'Saudi Arabia',
    'sn': 'Senegal',
    'rs': 'Serbia',
    'sc': 'Seychelles',
    'sl': 'Sierra Leone',
    'sg': 'Singapore',
    'sx': 'Sint Maarten (Dutch part)',
    'sk': 'Slovakia',
    'si': 'Slovenia',
    'sb': 'Solomon Islands',
    'so': 'Somalia',
    'za': 'South Africa',
    'gs': 'South Georgia and the South Sandwich Islands',
    'ss': 'South Sudan',
    'es': 'Spain',
    'lk': 'Sri Lanka',
    'sd': 'Sudan',
    'sr': 'Suriname',
    'sj': 'Svalbard and Jan Mayen[e]',
    'se': 'Sweden',
    'ch': 'Switzerland',
    'sy': 'Syrian Arab Republic',
    'tw': 'Taiwan, Province of China[b]',
    'tj': 'Tajikistan',
    'tz': 'Tanzania, United Republic of',
    'th': 'Thailand',
    'tl': 'Timor-Leste',
    'tg': 'Togo',
    'tk': 'Tokelau',
    'to': 'Tonga',
    'tt': 'Trinidad and Tobago',
    'tn': 'Tunisia',
    'tr': 'Türkiye',
    'tm': 'Turkmenistan',
    'tc': 'Turks and Caicos Islands',
    'tv': 'Tuvalu',
    'ug': 'Uganda',
    'ua': 'Ukraine',
    'ae': 'United Arab Emirates',
    'gb': 'United Kingdom of Great Britain and Northern Ireland',
    'us': 'United States of America',
    'um': 'United States Minor Outlying Islands[f]',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'vu': 'Vanuatu',
    've': 'Venezuela, Bolivarian Republic of',
    'vn': 'Viet Nam',
    'vg': 'Virgin Islands (British)',
    'vi': 'Virgin Islands (U.S.)',
    'wf': 'Wallis and Futuna',
    'eh': 'Western Sahara[b]',
    'ye': 'Yemen',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
}
